# Generated by Django 4.0.1 on 2022-01-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_caption', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(help_text='Enter Description', max_length=200)),
                ('media_url', models.TextField(help_text='Enter image/video url')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Enter where this card links to')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
