# Generated by Django 4.0.1 on 2022-01-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcards',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enter where this card links to'),
        ),
        migrations.AlterField(
            model_name='projectcards',
            name='media_url',
            field=models.URLField(help_text='Enter image/video url'),
        ),
    ]
