# Generated by Django 4.0.1 on 2022-01-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_projectcards_link_alter_projectcards_media_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCards',
            new_name='ProjectCard',
        ),
    ]
