# Generated by Django 4.0.1 on 2022-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_projectcard_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcard',
            name='img_caption',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Image caption'),
        ),
    ]
