# Generated by Django 4.0.1 on 2022-01-19 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_projectcard_img_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcard',
            name='media_url',
        ),
        migrations.AddField(
            model_name='projectcard',
            name='is_img',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcard',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='card_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'jpg', 'jpeg', 'png'])], verbose_name='Video or Image Background'),
        ),
    ]
