# Generated by Django 4.0.1 on 2022-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_projectcard_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcard',
            name='is_img',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
