# Generated by Django 4.0.1 on 2022-01-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_projectcard_is_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='show_caption',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Background File Extension'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='img_caption',
            field=models.CharField(default='a', help_text='What does this card represent?', max_length=10, verbose_name='Card Name'),
            preserve_default=False,
        ),
    ]
