# Generated by Django 4.0.1 on 2022-01-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_projectcard_show_caption_alter_projectcard_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcard',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
