# Generated by Django 4.0.1 on 2022-01-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_projectcard_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcard',
            name='order',
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='is_img',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this file an image'),
        ),
    ]
