# Generated by Django 4.0.1 on 2022-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_projectcard_order_alter_projectcard_is_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectcard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='is_img',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is the background an image'),
        ),
    ]
