# Generated by Django 4.0.1 on 2022-01-20 22:31

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_projectcard_options_projectcard_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
