# Generated by Django 4.0.1 on 2022-01-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_descriptionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='descriptionpage',
            name='slug',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
